import { useState } from "react";
import { useEmissionsRecords } from "../utils/useEmissionsRecords";
import {
  ChatBubbleLeftRightIcon,
  SparklesIcon,
  PaperAirplaneIcon,
  UserIcon,
} from "@heroicons/react/24/outline";

interface ChatMessage {
  id: string;
  sender: "user" | "ai";
  text: string;
  timestamp: string;
}

export default function Assistant() {
  const { records } = useEmissionsRecords();
  const [inputQuery, setInputQuery] = useState("");
  const [messages, setMessages] = useState<ChatMessage[]>([
    {
      id: "msg-1",
      sender: "ai",
      text: `Hello! I am your CarbonTrack AI Assistant. I have analyzed your ${records.length} logged environmental records totaling ${(records.reduce((s, r) => s + (r.emissions_t_co2e || 0), 0)).toFixed(2)} tCO₂e. Ask me any question about your Scope 1, Scope 2, or Scope 3 carbon footprint!`,
      timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
    },
  ]);

  const totalEmissions = records.reduce((s, r) => s + (r.emissions_t_co2e || 0), 0);
  const scope1 = records.filter((r) => r.scope === "scope1").reduce((s, r) => s + (r.emissions_t_co2e || 0), 0);
  const scope2 = records.filter((r) => r.scope === "scope2").reduce((s, r) => s + (r.emissions_t_co2e || 0), 0);
  const scope3 = records.filter((r) => r.scope === "scope3").reduce((s, r) => s + (r.emissions_t_co2e || 0), 0);

  // Find top category
  const categoryTotals: Record<string, number> = {};
  records.forEach((r) => {
    categoryTotals[r.category] = (categoryTotals[r.category] || 0) + (r.emissions_t_co2e || 0);
  });
  const sortedCategories = Object.entries(categoryTotals).sort((a, b) => b[1] - a[1]);
  const topCat = sortedCategories[0] || ["None", 0];

  const handleSend = (queryText?: string) => {
    const textToSend = queryText || inputQuery;
    if (!textToSend.trim()) return;

    const userMsg: ChatMessage = {
      id: `user-${Date.now()}`,
      sender: "user",
      text: textToSend,
      timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
    };

    let aiReplyText = "";
    const q = textToSend.toLowerCase();

    if (q.includes("total") || q.includes("overall") || q.includes("footprint")) {
      aiReplyText = `Your total enterprise carbon footprint across all logged records is **${totalEmissions.toFixed(2)} tCO₂e**.\n- Scope 1 Direct: **${scope1.toFixed(2)} tCO₂e**\n- Scope 2 Purchased Electricity: **${scope2.toFixed(2)} tCO₂e**\n- Scope 3 Value Chain: **${scope3.toFixed(2)} tCO₂e**`;
    } else if (q.includes("scope 3") || q.includes("cloud") || q.includes("supplier")) {
      aiReplyText = `Scope 3 accounts for **${scope3.toFixed(2)} tCO₂e** (${totalEmissions > 0 ? ((scope3 / totalEmissions) * 100).toFixed(1) : 0}% of your total). Your primary Scope 3 driver is **${sortedCategories.find(([c]) => c.includes("Cloud") || c.includes("Hardware") || c.includes("Travel"))?.[0] || "Purchased Services"}**.`;
    } else if (q.includes("reduce") || q.includes("cut") || q.includes("recommendation")) {
      aiReplyText = `Based on your highest hotspot (**${topCat[0]}** with **${topCat[1].toFixed(1)} tCO₂e**), my top recommendation is to procure 100% Renewable Energy Certificates (RECs) for your tech parks and migrate cloud compute to low-carbon AWS/GCP regions.`;
    } else if (q.includes("scope 1") || q.includes("diesel") || q.includes("fuel")) {
      aiReplyText = `Scope 1 direct emissions are currently **${scope1.toFixed(2)} tCO₂e**. This is generated by generator diesel and refrigerant leakage across your facilities.`;
    } else {
      aiReplyText = `Based on your dataset of ${records.length} records, your top emission category is **${topCat[0]}** generating **${topCat[1].toFixed(2)} tCO₂e** (${totalEmissions > 0 ? ((topCat[1] / totalEmissions) * 100).toFixed(1) : 0}% of enterprise footprint). You can add more data on the Upload Data page anytime!`;
    }

    const aiMsg: ChatMessage = {
      id: `ai-${Date.now()}`,
      sender: "ai",
      text: aiReplyText,
      timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
    };

    setMessages((prev) => [...prev, userMsg, aiMsg]);
    if (!queryText) setInputQuery("");
  };

  const samplePrompts = [
    "What is our total carbon footprint?",
    "Which category is our biggest carbon hotspot?",
    "How can we reduce Scope 2 emissions?",
    "Summarize our Scope 3 cloud footprint",
  ];

  return (
    <div className="space-y-6 pb-12">
      {/* HEADER */}
      <div className="border-b border-slate-200 pb-5">
        <div className="flex items-center gap-2 text-emerald-600 font-semibold text-xs tracking-wider uppercase">
          <ChatBubbleLeftRightIcon className="w-4 h-4" />
          AI Environmental Assistant
        </div>
        <h1 className="text-3xl font-bold text-slate-900 mt-1">CarbonTrack AI Assistant</h1>
        <p className="text-sm text-slate-500 mt-1">
          Ask conversational questions about your logged carbon emissions, reduction targets, and GHG Protocol standards.
        </p>
      </div>

      {/* CHAT CONTAINER */}
      <div className="bg-white border border-slate-200 rounded-3xl shadow-sm flex flex-col min-h-[520px] max-w-4xl mx-auto overflow-hidden">
        {/* CHAT MESSAGES STREAM */}
        <div className="flex-1 p-6 overflow-y-auto space-y-4 bg-slate-50/50">
          {messages.map((msg) => (
            <div
              key={msg.id}
              className={`flex items-start gap-3 ${msg.sender === "user" ? "flex-row-reverse" : ""}`}
            >
              <div
                className={`w-8 h-8 rounded-full flex items-center justify-center shrink-0 ${
                  msg.sender === "user" ? "bg-slate-900 text-white" : "bg-emerald-500 text-white"
                }`}
              >
                {msg.sender === "user" ? (
                  <UserIcon className="w-4 h-4" />
                ) : (
                  <SparklesIcon className="w-4 h-4" />
                )}
              </div>

              <div
                className={`max-w-lg rounded-2xl p-4 text-xs leading-relaxed shadow-sm ${
                  msg.sender === "user"
                    ? "bg-slate-900 text-white rounded-tr-none"
                    : "bg-white text-slate-800 border border-slate-200 rounded-tl-none whitespace-pre-line"
                }`}
              >
                <p>{msg.text}</p>
                <span
                  className={`text-[10px] block mt-2 text-right ${
                    msg.sender === "user" ? "text-slate-400" : "text-slate-400"
                  }`}
                >
                  {msg.timestamp}
                </span>
              </div>
            </div>
          ))}
        </div>

        {/* PROMPT CHIPS & INPUT BOX */}
        <div className="p-4 bg-white border-t border-slate-200 space-y-3">
          {/* Sample Prompts */}
          <div className="flex items-center gap-2 overflow-x-auto pb-1">
            <span className="text-[11px] font-bold text-slate-400 shrink-0">Suggested:</span>
            {samplePrompts.map((prompt) => (
              <button
                key={prompt}
                onClick={() => handleSend(prompt)}
                className="px-3 py-1 rounded-full bg-slate-100 hover:bg-emerald-50 hover:text-emerald-700 hover:border-emerald-200 border border-slate-200 text-slate-600 text-xs font-medium whitespace-nowrap transition"
              >
                {prompt}
              </button>
            ))}
          </div>

          {/* Text Input Box */}
          <form
            onSubmit={(e) => {
              e.preventDefault();
              handleSend();
            }}
            className="flex items-center gap-2"
          >
            <input
              type="text"
              placeholder="Ask AI Assistant about your carbon footprint..."
              value={inputQuery}
              onChange={(e) => setInputQuery(e.target.value)}
              className="flex-1 px-4 py-3 rounded-xl border border-slate-200 text-xs focus:outline-none focus:ring-2 focus:ring-emerald-500/20 focus:border-emerald-500 transition"
            />
            <button
              type="submit"
              className="px-4 py-3 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl text-xs font-bold transition flex items-center gap-1.5 shadow-sm"
            >
              <span>Send</span>
              <PaperAirplaneIcon className="w-4 h-4" />
            </button>
          </form>
        </div>
      </div>
    </div>
  );
}